version: '3.9'
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - ia_service

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  ia_service:
    build:
      context: ./ia_service
    container_name: ia_service
    ports:
      - "8001:8001"
    volumes:
      - ./ia_service:/app
    environment:
      OPENAI_API_KEY: "your-openai-api-key"

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
